<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_extend"
 *
 * Auto generated by Extension Builder 2016-12-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Additional fields for news',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Daniel Schoeneck',
    'author_email' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.1-10.4.99',
            'news' => ''
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];